// ======================================================================
// shared/catalogs/ups-dkc.js
// DKC UPS — серии Small Tower / Small Rack / SMALL+ / TwinDom (моноблоки)
// и Modulys (модульные, OEM Socomec). 10 моделей.
// Источник: DKC ИБП каталог 2023-2024.
// ======================================================================

export const DKC_UPSES = [
  // ── Small (1ph small online) ─────────────────────────────────────
  {
    id: 'dkc-small-1k', supplier: 'DKC',
    model: 'Small Tower 1 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 1, capacityKw: 0.9, phases: 1,
    efficiency: 90, cosPhi: 0.9,
    vdcMin: 24, vdcMax: 28, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC Small Tower datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 1 кВА · 1ф · Line-Interactive · Tower.',
  },
  {
    id: 'dkc-small-3k', supplier: 'DKC',
    model: 'Small Tower 3 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 3, capacityKw: 2.7, phases: 1,
    efficiency: 92, cosPhi: 0.9,
    vdcMin: 72, vdcMax: 96, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC Small Tower datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 3 кВА · 1ф · Line-Interactive.',
  },
  {
    id: 'dkc-small-6k', supplier: 'DKC',
    model: 'SMALL+ 6 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 6, capacityKw: 5.4, phases: 1,
    efficiency: 95, cosPhi: 0.9,
    vdcMin: 192, vdcMax: 240, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC SMALL+ datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 6 кВА · 1ф · Online VFI.',
  },
  {
    id: 'dkc-small-10k', supplier: 'DKC',
    model: 'SMALL+ 10 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 10, capacityKw: 9, phases: 1,
    efficiency: 95, cosPhi: 0.9,
    vdcMin: 192, vdcMax: 240, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC SMALL+ datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 10 кВА · 1ф · Online VFI.',
  },
  // ── TwinDom (3ph monoblock) ──────────────────────────────────────
  {
    id: 'dkc-twindom-20k', supplier: 'DKC',
    model: 'TwinDom 20 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 20, capacityKw: 20, phases: 3,
    efficiency: 95, cosPhi: 1.0,
    vdcMin: 240, vdcMax: 360, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC TwinDom datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 20 кВА · 3ф.',
  },
  {
    id: 'dkc-twindom-40k', supplier: 'DKC',
    model: 'TwinDom 40 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 40, capacityKw: 40, phases: 3,
    efficiency: 96, cosPhi: 1.0,
    vdcMin: 360, vdcMax: 480, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC TwinDom datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 40 кВА · 3ф.',
  },
  {
    id: 'dkc-twindom-80k', supplier: 'DKC',
    model: 'TwinDom 80 kVA', kind: 'ups-integrated', upsType: 'monoblock',
    capacityKva: 80, capacityKw: 80, phases: 3,
    efficiency: 96, cosPhi: 1.0,
    vdcMin: 384, vdcMax: 480, inputs: 1, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC TwinDom datasheet',
    importedAt: 0, custom: false,
    notes: 'Моноблок 80 кВА · 3ф.',
  },
  // ── Modulys (modular, OEM Socomec) ───────────────────────────────
  {
    id: 'dkc-modulys-25k', supplier: 'DKC',
    model: 'Modulys GP 25', kind: 'ups-integrated', upsType: 'modular',
    capacityKva: 25, capacityKw: 25, phases: 3,
    frameKw: 200, moduleKwRated: 25, moduleSlots: 8,
    efficiency: 96, cosPhi: 1.0,
    vdcMin: 360, vdcMax: 480, inputs: 2, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC Modulys GP datasheet',
    importedAt: 0, custom: false,
    notes: 'Модульный 25 кВт (1×25 в фрейме 200) · 3ф · Hot-swap.',
  },
  {
    id: 'dkc-modulys-100k', supplier: 'DKC',
    model: 'Modulys GP 100', kind: 'ups-integrated', upsType: 'modular',
    capacityKva: 100, capacityKw: 100, phases: 3,
    frameKw: 200, moduleKwRated: 25, moduleSlots: 8,
    efficiency: 96.5, cosPhi: 1.0,
    vdcMin: 384, vdcMax: 480, inputs: 2, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC Modulys GP datasheet',
    importedAt: 0, custom: false,
    notes: 'Модульный 100 кВт (4×25) · 3ф.',
  },
  {
    id: 'dkc-modulys-xl-300k', supplier: 'DKC',
    model: 'Modulys XL 300', kind: 'ups-integrated', upsType: 'modular',
    capacityKva: 300, capacityKw: 300, phases: 3,
    frameKw: 600, moduleKwRated: 50, moduleSlots: 12,
    efficiency: 97, cosPhi: 1.0,
    vdcMin: 432, vdcMax: 540, inputs: 2, outputs: 1,
    batteryChemistry: 'vrla',
    source: 'DKC Modulys XL datasheet',
    importedAt: 0, custom: false,
    notes: 'Модульный 300 кВт (6×50 в фрейме 600) · 3ф · ЦОД-класс.',
  },
];
