// service/catalog/wizards/chiller-to.js — ТО чиллера. Phase 42 v0.60.109.

export const WIZARD_CHILLER_TO = {
  id: 'wz-seed-chiller-to',
  icon: '❄',
  title: 'ТО чиллера / холодильной машины',
  description: 'Регламентное обслуживание холодильной машины. Мастер задаёт мощность и тип хладагента, предлагает дозаправку, проверки и замену расходников.',
  appliesTo: ['maintenance'],

  params: [
    {
      id: 'capKw',
      label: 'Холодопроизводительность, кВт',
      type: 'number',
      min: 5,
      max: 5000,
      step: 5,
      default: 200,
      required: true,
      tip: 'Номинальная холодопроизводительность чиллера по паспорту.',
    },
    {
      id: 'refrigerant',
      label: 'Хладагент',
      type: 'choice',
      options: [
        { v: 'R410A', l: 'R410A' },
        { v: 'R32',   l: 'R32' },
        { v: 'R134a', l: 'R134a' },
        { v: 'R407C', l: 'R407C' },
        { v: 'R290',  l: 'R290 (пропан, A3)' },
        { v: 'R513A', l: 'R513A' },
        { v: 'R1234ze', l: 'R1234ze' },
      ],
      default: 'R410A',
      tip: 'Тип хладагента в контуре. Влияет на цену дозаправки и требования к работам (А3-горючий = особые меры).',
    },
    {
      id: 'compressorType',
      label: 'Тип компрессора',
      type: 'choice',
      options: [
        { v: 'scroll', l: 'Spiral / Scroll' },
        { v: 'screw',  l: 'Винтовой' },
        { v: 'centrifugal', l: 'Центробежный' },
        { v: 'piston', l: 'Поршневой' },
      ],
      default: 'scroll',
      tip: 'Влияет на работы по маслу и проверки.',
    },
    {
      id: 'condenserType',
      label: 'Конденсатор',
      type: 'choice',
      options: [
        { v: 'air',   l: 'Воздушный' },
        { v: 'water', l: 'Водяной (с градирней)' },
      ],
      default: 'air',
      tip: 'Воздушный требует чистки рёбер; водяной — обслуживания градирни / промывки.',
    },
    {
      id: 'periodMonths',
      label: 'Периодичность ТО, мес.',
      type: 'number',
      min: 1,
      max: 12,
      default: 3,
    },
  ],

  suggestions: [
    {
      group: '🔧 Регламентные работы',
      rules: [
        {
          when: 'true',
          label: 'Регламентное ТО чиллера (визит)',
          qty: 1,
          unit: 'выезд',
          category: 'labor',
          costPrice: 35000,
          clientPrice: 65000,
          ask: 'Добавить выезд бригады для ТО?',
        },
        {
          when: 'true',
          label: 'Проверка давлений хладагента',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 5000,
          clientPrice: 9500,
          ask: 'Добавить проверку давлений?',
        },
        {
          when: 'condenserType === "air"',
          label: 'Чистка рёбер конденсатора (воздушный)',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 8000,
          clientPrice: 15000,
          ask: 'Воздушный конденсатор — добавить чистку рёбер?',
        },
        {
          when: 'condenserType === "water"',
          label: 'Промывка водяного конденсатора',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 18000,
          clientPrice: 32000,
          ask: 'Водяной конденсатор — добавить промывку?',
        },
        {
          when: 'compressorType === "screw" && periodMonths >= 6',
          label: 'Замена масла винтового компрессора',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 12000,
          clientPrice: 22000,
          ask: 'Винтовой компрессор + период {periodMonths} мес. — заменить масло?',
        },
        {
          when: 'capKw >= 500',
          label: 'Калибровка терморегулирующих вентилей',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 9000,
          clientPrice: 17000,
          ask: 'Большая машина {capKw} кВт — добавить калибровку ТРВ?',
        },
      ],
    },
    {
      group: '🧪 Хладагент / расходники',
      rules: [
        {
          when: 'refrigerant === "R410A"',
          label: 'Хладагент R410A (дозаправка)',
          qty: 'Math.max(1, Math.round(capKw / 200))',
          unit: 'кг',
          category: 'material',
          costPrice: 3500,
          clientPrice: 5500,
          ask: 'R410A — {qty} кг для дозаправки?',
        },
        {
          when: 'refrigerant === "R32"',
          label: 'Хладагент R32 (дозаправка)',
          qty: 'Math.max(1, Math.round(capKw / 200))',
          unit: 'кг',
          category: 'material',
          costPrice: 4200,
          clientPrice: 6500,
          ask: 'R32 — {qty} кг?',
        },
        {
          when: 'refrigerant === "R134a"',
          label: 'Хладагент R134a (дозаправка)',
          qty: 'Math.max(1, Math.round(capKw / 200))',
          unit: 'кг',
          category: 'material',
          costPrice: 4800,
          clientPrice: 7200,
          ask: 'R134a — {qty} кг?',
        },
        {
          when: 'refrigerant === "R407C"',
          label: 'Хладагент R407C (дозаправка)',
          qty: 'Math.max(1, Math.round(capKw / 200))',
          unit: 'кг',
          category: 'material',
          costPrice: 5200,
          clientPrice: 8000,
          ask: 'R407C — {qty} кг?',
        },
        {
          when: 'refrigerant === "R290"',
          label: 'Хладагент R290 пропан (дозаправка, A3 — горючий)',
          qty: 'Math.max(1, Math.round(capKw / 250))',
          unit: 'кг',
          category: 'material',
          costPrice: 1800,
          clientPrice: 3500,
          ask: 'R290 — {qty} кг? Горючий — нужны спецмеры (см. ниже).',
        },
        {
          when: 'refrigerant === "R290"',
          label: 'Доплата за А3-работы (искробезопасные инструменты)',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 8000,
          clientPrice: 14000,
          ask: 'R290 (горючий) — добавить доплату за искробезопасные работы?',
        },
      ],
    },
  ],
};
