// service/catalog/wizards/ups-to.js — ТО ИБП. Phase 42 v0.60.109.

export const WIZARD_UPS_TO = {
  id: 'wz-seed-ups-to',
  icon: '🔋',
  title: 'ТО ИБП и АКБ',
  description: 'Регламентное обслуживание ИБП. Мастер задаёт мощность, тип АКБ и кол-во батарей; предлагает проверки, dummy-load test (по периодичности), замену расходников.',
  appliesTo: ['maintenance'],

  params: [
    {
      id: 'kva',
      label: 'Мощность ИБП, кВА',
      type: 'number',
      min: 1,
      max: 5000,
      step: 5,
      default: 200,
      required: true,
      tip: 'Номинальная полная мощность ИБП.',
    },
    {
      id: 'batteryTech',
      label: 'Тип АКБ',
      type: 'choice',
      options: [
        { v: 'vrla',    l: 'VRLA (свинцово-кислотные)' },
        { v: 'lifepo4', l: 'Li-Ion (LFP)' },
        { v: 'gel',     l: 'GEL' },
        { v: 'agm',     l: 'AGM' },
      ],
      default: 'vrla',
      tip: 'VRLA требуют ежегодной проверки емкости. Li-Ion — диагностика BMS.',
    },
    {
      id: 'batteryCount',
      label: 'Кол-во АКБ в стринге',
      type: 'number',
      min: 8,
      max: 240,
      default: 40,
      tip: 'Сколько штук в одной нитке (стринге). Для 480В DC обычно 40 шт.',
    },
    {
      id: 'stringCount',
      label: 'Кол-во стрингов (параллельных ниток)',
      type: 'number',
      min: 1,
      max: 12,
      default: 1,
      tip: 'Параллельные нитки АКБ для увеличения автономии или резерва.',
    },
    {
      id: 'periodMonths',
      label: 'Периодичность ТО, мес.',
      type: 'number',
      min: 1,
      max: 24,
      default: 6,
    },
    {
      id: 'lastBatteryTestMonths',
      label: 'Сколько мес. с прошлого dummy-load теста',
      type: 'number',
      min: 0,
      max: 60,
      default: 12,
      tip: 'Dummy-load (тест ёмкости АКБ) обычно раз в 12 мес. Если давно не делали — добавится.',
    },
  ],

  suggestions: [
    {
      group: '🔧 Регламентные работы',
      rules: [
        {
          when: 'true',
          label: 'Регламентное ТО ИБП (визит)',
          qty: 1,
          unit: 'выезд',
          category: 'labor',
          costPrice: 30000,
          clientPrice: 55000,
          ask: 'Добавить выезд бригады для ТО ИБП?',
        },
        {
          when: 'true',
          label: 'Термоснимок ИБП и АКБ-стойки (тепловизор)',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 4000,
          clientPrice: 8000,
          ask: 'Добавить термосъёмку (выявление проблемных контактов)?',
        },
        {
          when: 'lastBatteryTestMonths >= 12',
          label: 'Dummy-load тест АКБ (тест ёмкости)',
          qty: 1,
          unit: 'комплект',
          category: 'labor',
          costPrice: 25000,
          clientPrice: 48000,
          ask: 'Прошло {lastBatteryTestMonths} мес. с прошлого теста — добавить dummy-load?',
        },
        {
          when: 'batteryTech === "vrla" || batteryTech === "gel" || batteryTech === "agm"',
          label: 'Контроль межэлементных соединений АКБ (момент затяжки)',
          qty: '(batteryCount * stringCount)',
          unit: 'шт',
          category: 'labor',
          costPrice: 80,
          clientPrice: 150,
          ask: 'Свинцово-кислотные АКБ — контроль соединений {qty} шт?',
        },
        {
          when: 'batteryTech === "lifepo4"',
          label: 'Диагностика BMS Li-Ion стринга',
          qty: 'stringCount',
          unit: 'комплект',
          category: 'labor',
          costPrice: 5000,
          clientPrice: 9500,
          ask: 'Li-Ion — диагностика BMS {qty} стринга?',
        },
        {
          when: 'kva >= 500',
          label: 'Замена вентиляторов охлаждения (большой ИБП по часам)',
          qty: 'Math.max(2, Math.ceil(kva / 200))',
          unit: 'шт',
          category: 'material',
          costPrice: 6000,
          clientPrice: 11000,
          ask: 'Большой ИБП {kva} кВА — заменить {qty} вентилятор(а/ов) по часам наработки?',
        },
      ],
    },
    {
      group: '📦 Расходники',
      rules: [
        {
          when: 'batteryTech === "vrla" && periodMonths >= 12',
          label: 'Дистиллированная вода (доливка VRLA)',
          qty: '(batteryCount * stringCount * 0.05)',  // ~50 мл на банку при ТО
          unit: 'л',
          category: 'material',
          costPrice: 200,
          clientPrice: 450,
          ask: 'VRLA + годовое ТО — {qty} л дистиллированной воды?',
        },
        {
          when: 'true',
          label: 'Чистящие материалы (изопропил, безворсовые салфетки)',
          qty: 1,
          unit: 'комплект',
          category: 'material',
          costPrice: 800,
          clientPrice: 1600,
          ask: 'Добавить чистящий комплект?',
        },
      ],
    },
  ],
};
